#EDA constants
#Thresholds
CORR_THRESHOLD = 0.2
Z_SCR_THRESHOLD = 2
OUTLIER_METHOD = 'WINSOR'

#Attributes
ATTR = ['PER_TS_YIELD','DC_POWER','AC_POWER','DAILY_YIELD','TOTAL_YIELD','AMBIENT_TEMPERATURE','MODULE_TEMPERATURE','IRRADIATION','INVERTER_ID']
TIME_INVARIANT_ATTR = ['AMBIENT_TEMPERATURE','MODULE_TEMPERATURE','IRRADIATION']
TIME_VARIANT_ATTR = ['DC_POWER','AC_POWER','DAILY_YIELD','TOTAL_YIELD','PER_TS_YIELD']
IDENTIFIERS = ['DATE','PLANT_ID','INVERTER_ID','PANEL_ID']

#Modelling
SPLIT_PCT = 0.8